<<<<<<< HEAD
# Generated by Django 4.2 on 2024-03-10 05:07
=======
# Generated by Django 4.2 on 2024-03-10 05:27
>>>>>>> cd6fcf34b6f07da6b76b945d2d93919221d2fd80

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
