# Generated by Django 4.2 on 2024-03-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
