# Generated by Django 4.2 on 2024-02-29 03:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None, null=True),
        ),
    ]
