# Generated by Django 5.0.1 on 2024-02-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='potter',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tool_of_pottery',
        ),
        migrations.RemoveField(
            model_name='image',
            name='type_of_pottery',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.RemoveField(
            model_name='potter',
            name='images',
        ),
        migrations.RemoveField(
            model_name='techniquemakingpottery',
            name='images',
        ),
        migrations.RemoveField(
            model_name='toolpottery',
            name='images',
        ),
        migrations.RemoveField(
            model_name='typepottery',
            name='images',
        ),
        migrations.AddField(
            model_name='potter',
            name='images',
            field=models.ManyToManyField(to='home.image'),
        ),
        migrations.AddField(
            model_name='techniquemakingpottery',
            name='images',
            field=models.ManyToManyField(to='home.image'),
        ),
        migrations.AddField(
            model_name='toolpottery',
            name='images',
            field=models.ManyToManyField(to='home.image'),
        ),
        migrations.AddField(
            model_name='typepottery',
            name='images',
            field=models.ManyToManyField(to='home.image'),
        ),
    ]
