# Generated by Django 5.0.1 on 2024-02-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='province_images/'),
        ),
    ]
