# Generated by Django 5.0.1 on 2024-02-15 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_province_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='images',
        ),
        migrations.CreateModel(
            name='ProvinceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='province_images/')),
                ('province', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.province')),
            ],
        ),
    ]
