# Generated by Django 4.2 on 2024-02-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_province_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='potter',
            name='short_description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
