# Generated by Django 5.0.1 on 2024-02-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_image_potter_remove_image_tool_of_pottery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potter',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2),
        ),
    ]
