# Generated by Django 5.0.1 on 2024-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_potter_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='potter',
            name='inheritance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
