# Generated by Django 5.0.1 on 2024-02-12 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_potter_inheritance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='province',
            name='created_at',
        ),
        migrations.AddField(
            model_name='potter',
            name='type_of_pottery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.typepottery'),
        ),
    ]
