# Generated by Django 4.2 on 2024-02-20 03:10

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_potter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potter',
            name='commune_of_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commune_of_address', to='home.commune'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='commune_of_pob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commune_of_pob', to='home.commune'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='district_of_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_of_address', to='home.district'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='district_of_pob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_of_pob', to='home.district'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='province_of_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_of_address', to='home.province'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='province_of_pob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_of_pob', to='home.province'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='village_of_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_of_address', to='home.village'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='village_of_pob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_of_pob', to='home.village'),
        ),
    ]
