# Generated by Django 4.2 on 2024-02-20 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_potter_commune_of_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potter',
            name='commune_of_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commune_of_address', to='home.commune'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='commune_of_pob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commune_of_pob', to='home.commune'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='district_of_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_of_address', to='home.district'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='district_of_pob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_of_pob', to='home.district'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='province_of_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_of_address', to='home.province'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='province_of_pob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_of_pob', to='home.province'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='village_of_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_of_address', to='home.village'),
        ),
        migrations.AlterField(
            model_name='potter',
            name='village_of_pob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_of_pob', to='home.village'),
        ),
    ]
