# Generated by Django 5.0.1 on 2024-02-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_commune_created_at_remove_district_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potter',
            name='inheritance',
            field=models.CharField(max_length=255),
        ),
    ]
