# Generated by Django 4.2 on 2024-02-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_potter_commune_of_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potter',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
