# Generated by Django 4.2 on 2024-02-21 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_potter_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquemakingpottery',
            name='potter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.potter'),
        ),
    ]
