# Generated by Django 4.2 on 2024-02-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_techniquemakingpottery_potter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniquemakingpottery',
            name='json_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
