# Generated by Django 4.2 on 2024-02-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_techniquemakingpottery_json_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potter',
            old_name='description',
            new_name='potter_description',
        ),
    ]
