# Generated by Django 5.0.1 on 2024-02-13 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_potter_url_google_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potter',
            name='images',
        ),
        migrations.RemoveField(
            model_name='typepottery',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='potter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.potter'),
        ),
    ]
