# Generated by Django 4.2 on 2024-02-21 06:54

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_description_potter_potter_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potter',
            name='potter_description',
        ),
        migrations.AddField(
            model_name='potter',
            name='describe',
            field=django_ckeditor_5.fields.CKEditor5Field(default=None, verbose_name='Potter Description'),
        ),
    ]
