# Generated by Django 5.0.1 on 2024-02-13 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_potter_images_remove_typepottery_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='potter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.potter'),
        ),
    ]
