# Generated by Django 4.2 on 2024-02-28 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_potter_potter_description_potter_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potter',
            name='inventory_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='techniquemakingpottery',
            name='potter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potter', to='home.potter'),
        ),
    ]
