# Generated by Django 5.0.1 on 2024-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_image_url_image_image_alter_image_potter'),
    ]

    operations = [
        migrations.AddField(
            model_name='potter',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='potter',
            name='x_coordinate',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potter',
            name='y_coordinate',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='potter',
            name='youtube_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='potter',
            name='url_google_map',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
