# Generated by Django 5.0.1 on 2024-02-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_potter_description_potter_x_coordinate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potter',
            name='url_google_map',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='potter',
            name='youtube_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
