# Generated by Django 4.2 on 2024-02-28 02:47

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_potter_inventory_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=None, verbose_name='Province Description'),
        ),
    ]
