# Generated by Django 5.0.1 on 2024-02-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_potter_url_google_map_alter_potter_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potter',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='potter',
            name='inheritance',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
