# Generated by Django 4.2 on 2024-02-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_category_create_at_alter_post_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
