# Generated by Django 4.2 on 2024-03-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedlive',
            name='embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
